version: "3"
services:
  web:
    image: storefront:latest
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=foobar
      - MONGO_HOST=db
    depends_on:
      - db
  db:
    image: mongo
    ports:
     - "27017:27017"
  nginx:
    image: nginx:latest 
    ports:
      - 1337:80
    depends_on:
      - web
