version: "3"
services:
  web:
    build:
      context: ../storefront
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../storefront/:/usr/src/bookstore/storefront
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - SECRET_KEY=foobar
