version: "3"
services:
  db:
    image: mongo
    ports:
      - 27017:27017
  web:
    build:
      context: ../storefront
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/storefront/staticfiles
    command: gunicorn storefront.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - MONGO_HOST=db
    depends_on:
      - db
  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/storefront/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
