version: "3"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build:
      context: ../storefront
      dockerfile: Dockerfile
    volumes:
      - ../storefront/:/usr/src/storefront
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - MONGO_HOST=db
    depends_on:
      - db
  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - 1337:80
    depends_on:
      - web
